name: Hello Anji

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "this is anji output -3"

      - name: Display current date
        run: date

      - name: List repository files
        run: ls -la
      
      - name: host name
        run: hostname -i
