name: Hello World

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: [selfhosted, linux, x64, aws]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello, World!"

      - name: Display current date
        run: date

      - name: List repository files
        run: ls -la